language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer require --dev --no-update squizlabs/php_codesniffer
  - travis_retry composer install --prefer-dist --no-interaction

notifications:
    email: false

script:
  - vendor/bin/phpcs --colors -p --standard=PSR2 --encoding=utf-8 -n src/
  - vendor/bin/phpunit --coverage-text --exclude-group integration

matrix:
  allow_failures:
    - php: hhvm